name: CI

on: [pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Check formatting
        run: npm run format
      - name: Check linting
        run: npm run lint
      - name: Check types
        run: npm run typecheck

  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Build extension
        run: |
          npm run zip
          version=$(node -p "require('./package.json').version")
          unzip ".output/samay-${version}-chrome.zip" -d ".output/samay-${version}-chrome"
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run tests
        run: npm run test

      # Upload test results on failure
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 1

  deploy-test-result:
    if: always() && needs.test.result == 'failure'
    needs: test

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
      - name: Deploy to Netlify
        run: npx netlify-cli deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --dir playwright-report --json | jq -r '.deploy_url' > deploy-url.txt
      # This requires "Settings > Actions > General > Workflow permissions > Read and write permissions" to be selected
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('node:fs');
            const deployUrl = fs.readFileSync('deploy-url.txt', 'utf-8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Test failed: ${deployUrl}`
            });
